### ISSUE TITLE
Headless Chrome Bug: update 2.31.0 Chrome.WebDriver.ChromeDriver 

### ISSUE THREAD

**Issue by grock90** [jbaranda/nupkg-selenium-webdrivers#13]
I'm curious to know if/when a dependency will be taken upon the update version of the Chrome.WebDriver.ChromerDriver v2.31.0 to resolve an issue where the headless chrome still opens a blank visible chrome instance in taskbar.

Thank you for taking this into consideration.  Here's the link that hinted toward the resolution: https://stackoverflow.com/questions/45533357/launching-chrome-headless-in-selenium-webdriver-still-results-in-a-blank-browser

**Comment by jbaranda** [comment]
@grock90 Sorry for long delay in responding...  (did not realize other people were following this repo and/or were reporting issues)

This repo provides way to build your own nuget package for the different WebDriver binaries (via the [BuildPackage.bat](https://github.com/jbaranda/nupkg-selenium-webdrivers/blob/master/BuildPackage.bat) file and the drivers related nuspec file) so it can be included in your solution ([without having to commit the actual binary files to your project](https://github.com/jbaranda/nupkg-selenium-webdrivers#where-is-each-webdriver-binary-file-saved-to))

This is not the official ChromeDriver repo so any issues related to it's WebDriver implementation/client libraries should be reported through those [channels](http://chromedriver.chromium.org/help)

The [Readme documentation provides](https://github.com/jbaranda/nupkg-selenium-webdrivers#how-to-build-each-nuget-package) some examples of the script usage if you want to maintain and build your own nuget package.

I uploaded these packages to nuget to use in your solution as described in the readme if you prefer not to maintain your own packages

Again, sorry for the long delay in responding

Jeffrey
