### ISSUE TITLE
Update Chrome and IE drivers

### ISSUE THREAD

**Issue by habib535** [jbaranda/nupkg-selenium-webdrivers#14]
Hi, Can you please update Chrome to 2.31 and IE to 3.5
I would've loved to create a pull request myself :)

**Comment by jbaranda** [comment]
@habib535 Sorry for long delay in responding...  (did not realize other people were following this repo and/or were reporting issues)

I have updated Chrome and IE to the latest available versions (2.40 and 3.13 respectively)

Again, sorry for the long delay in responding

Jeffrey
