### ISSUE TITLE
Update to ChromeDriver 2.32.0 Resolves Chrome scrolling issue

### ISSUE THREAD

**Issue by grock90** [jbaranda/nupkg-selenium-webdrivers#17]
Please update to ChromeDriver 2.32.0 as it resolves the recently introduced bugs by Chrome v61 & v62 that breaks most automation due to a 'smooth scrolling' feature.   Unfortunately, we've had to introduce workarounds to prevent tests from failing until this version is made available. 

https://github.com/SeleniumHQ/selenium/issues/4680 

- Fixes a bug where Chromedriver fails to click due to page scrolling changes in Chrome 61+.
- Fixes a bug where Chromedriver fails to delete cookies in Chrome 62+.
- Fixes a bug where Chromedriver fails to retrieve default prompt text in Chrome 62+.

https://sites.google.com/a/chromium.org/chromedriver/downloads

**Comment by Termiux** [comment]
Commit 6d8a5948761834681d2dd0f4bb0b600547d4b31 addressed this
