### ISSUE TITLE
Button click is not working in IE(3.12.0) and Firefox drivers (0.20.0) in tr tag

### ISSUE THREAD

**Issue by Pandiyarajk** [jbaranda/nupkg-selenium-webdrivers#32]
Button click is not working in IE(3.12.0) and Firefox drivers (0.20.0) in Table Row (tr)

**Comment by jbaranda** [comment]
@Pandiyarajk  Sorry for long delay in responding...  (did not realize other people were following this repo and/or were reporting issues)

This repo provides way to build your own nuget package for the different WebDriver binaries (via the [BuildPackage.bat](https://github.com/jbaranda/nupkg-selenium-webdrivers/blob/master/BuildPackage.bat) file and the drivers related nuspec file) so it can be included in your solution ([without having to commit the actual binary files to your project](https://github.com/jbaranda/nupkg-selenium-webdrivers#where-is-each-webdriver-binary-file-saved-to))

This is not the official IE Driver Server or Firefox WebDriver repos so any issues related to it's WebDriver implementation/client libraries should be reported through those proper channels:
[IEDriverServer](https://github.com/SeleniumHQ/selenium/issues?utf8=✓&q=is%3Aissue+is%3Aopen+iedriver)
[Firefox WebDriver](https://github.com/mozilla/geckodriver/issues)

The [Readme documentation provides](https://github.com/jbaranda/nupkg-selenium-webdrivers#how-to-build-each-nuget-package) some examples of the script usage if you want to maintain and build your own nuget package.

I uploaded these packages to nuget to use in your solution as described in the readme if you prefer not to maintain your own packages

Again, sorry for the long delay in responding

Jeffrey
