### ISSUE TITLE
Update ChromeDriver and GeckoDriver and MSWebDriver

### ISSUE THREAD

**Issue by qaqz111** [jbaranda/nupkg-selenium-webdrivers#40]
Hi, please update chromedriver(2.42+) and geckodriver(0.22+), and can you add support for MicrosoftWebDriver(17134+) which was used for Edge?

MSWebDriver
https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/

**Comment by jbaranda** [comment]
@qaqz111 Updated the nuget packages for Chrome and Firefox to 2.42 and 0.22.0 respectively
