### ISSUE TITLE
Update Selenium.Chrome.WebDriver to 75.0.3770.8

### ISSUE THREAD

**Issue by kwilson-93** [jbaranda/nupkg-selenium-webdrivers#51]
hi :)

Can you update Selenium.Chrome.WebDriver to 75.0.3770.8 please ?

Thanks !

**Comment by kwilson-93** [comment]
@jbaranda is this possible soon please :) ?

**Comment by otto-gebb** [comment]
@jbaranda I would also be thankful for the update.

**Comment by kwilson-93** [comment]
hi @otto-gebb , I just changed packages to jsakamoto's "Selenium.WebDriver.ChromeDriver" package, as by the looks of it this might be a long time before it's updated.

**Comment by jbaranda** [comment]
Nuget package has been [updated](https://www.nuget.org/packages/Selenium.Chrome.WebDriver/75.0.0) and contains [Chromedriver v75.0.3770.140](https://chromedriver.storage.googleapis.com/index.html?path=75.0.3770.140/) latest stable release 👍
