### ISSUE TITLE
Update Selenium.Chrome.WebDriver to 77.0.3865.40

### ISSUE THREAD

**Issue by ilhanoztozlu** [jbaranda/nupkg-selenium-webdrivers#56]
Hi @jbaranda 

Can you update Selenium.Chrome.WebDriver to 77.0.3865.40 please ?

Thank you

**Comment by jbaranda** [comment]
Updated the [nuget](https://www.nuget.org/packages/Selenium.Chrome.WebDriver/85.0.0) package to use [ChromeDriver v85.0.4183.87](https://chromedriver.storage.googleapis.com/index.html?path=85.0.4183.87/)

Will try to update these nuget in a shorter cadence in the future but may I suggest looking at [WebDriverManager.Net](https://github.com/rosolko/WebDriverManager.Net) as it provides as solution to managing new/updated webdriver binaries pretty seamlessly imo
