### ISSUE TITLE
Update Selenium.Chrome.WebDriver to version 80

### ISSUE THREAD

**Issue by isak-keymer** [jbaranda/nupkg-selenium-webdrivers#62]
Hello, could you please update the web driver for chrome to version 80.

Thanks in advance
Isak

**Comment by GoranHalvarsson** [comment]
If not then I have to go for - https://github.com/jsakamoto/nupkg-selenium-webdriver-chromedriver/

**Comment by jbaranda** [comment]
Updated the [nuget](https://www.nuget.org/packages/Selenium.Chrome.WebDriver/85.0.0) package to use [ChromeDriver v85.0.4183.87](https://chromedriver.storage.googleapis.com/index.html?path=85.0.4183.87/)

Will try to update these nuget in a shorter cadence in the future but may I suggest looking at [WebDriverManager.Net](https://github.com/rosolko/WebDriverManager.Net) as it provides as solution to managing new/updated webdriver binaries pretty seamlessly imo
