### ISSUE TITLE
Update Selenium.Chrome.WebDriver to version 83

### ISSUE THREAD

**Issue by farinha** [jbaranda/nupkg-selenium-webdrivers#64]
Can ChromeDriver please be updated to version 83?

Also, would it be possible to have it so that it doesn't fail completely when a new version of Chrome is released?
Don't know if it's possible, but some kind of warning would be better than an exception that makes all the tests start failing overnight:

> System.TypeInitializationException: The type initializer for 'XXXXXXXXXX' threw an exception. ---> System.InvalidOperationException: session not created: This version of ChromeDriver only supports Chrome version 81 (SessionNotCreated)

Thanks in advance!

**Comment by WillieLouw** [comment]
Would also appreciate an update where it does not fail complete when Chrome is automatically updated to a newer version, as Farinha mentioned. Trying to find working version for Chrome 83.0.4103.61.

**Comment by jbaranda** [comment]
Updated the [nuget](https://www.nuget.org/packages/Selenium.Chrome.WebDriver/85.0.0) package to use [ChromeDriver v85.0.4183.87](https://chromedriver.storage.googleapis.com/index.html?path=85.0.4183.87/)

Will try to update these nuget in a shorter cadence in the future but may I suggest looking at [WebDriverManager.Net](https://github.com/rosolko/WebDriverManager.Net) as it provides as solution to managing new/updated webdriver binaries pretty seamlessly imo
