### ISSUE TITLE
Version 85

### ISSUE THREAD

**Issue by Kellen-Stuart** [jbaranda/nupkg-selenium-webdrivers#67]
Can we please get support for ChromeDriver 85?

**Comment by bluewinder** [comment]
Found a solution to solve this issue, go to Google download chromedriver win32 latest version from https://chromedriver.storage.googleapis.com/index.html?path=85.0.4183.87/, and then extract and replace the chromedriver.exe file in your project folder, problem solved for me.

**Comment by farinha** [comment]
Another option might be switching to another package. This one seems to work in a very similar way, and was updated very quickly after the latest Chrome release:

https://www.nuget.org/packages/Selenium.WebDriver.ChromeDriver/

**Comment by ajdepersio** [comment]
This PR adds support for chrome 85 https://github.com/jbaranda/nupkg-selenium-webdrivers/pull/68

Until that is merged in, I can confirm that the package from @farinha comment works as well.

**Comment by jbaranda** [comment]
Updated the [nuget](https://www.nuget.org/packages/Selenium.Chrome.WebDriver/85.0.0) package to use [ChromeDriver v85.0.4183.87](https://chromedriver.storage.googleapis.com/index.html?path=85.0.4183.87/)

Will try to update these nuget in a shorter cadence in the future but may I suggest looking at [WebDriverManager.Net](https://github.com/rosolko/WebDriverManager.Net) as it provides as solution to managing new/updated webdriver binaries pretty seamlessly imo
